/* eslint-disable react-native/no-inline-styles */
import React, {Fragment} from 'react';
import {
  StyleSheet,
  View,
  Text,
  Dimensions,
  FlatList,
  TouchableOpacity,
  ViewPagerAndroid,
  Image,
  Alert,
} from 'react-native';


var styles = StyleSheet.create({
  navBar: {
    backgroundColor: adultLight,
  },
  navButton: {
    color: 'white',
    margin: 10 * ratio,
    fontFamily: 'Roboto-Regular',
    fontSize: 14.333 * ratio,
  },
  navTitle: {
    color: 'white',
    marginTop: 10 * ratio,
    marginBottom: 10 * ratio,
    textAlign: 'center',
    fontSize: 17.199 * ratio,
    fontFamily: 'AGBookRounded-Regular',
  },
  main: {
    flex: 1,
    paddingTop: 55,
    backgroundColor: 'white',
  },
  wrapper: {
    flex: 1,
    width: width,
  },
  container: {
    flex: 1,
    alignItems: 'flex-start',
  },
  textContainer: {
    alignSelf: 'stretch',
    alignItems: 'flex-start',
    padding: 15,
    paddingBottom: 5,
    paddingTop: 5,
  },
  navRow: {
    alignSelf: 'stretch',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  title: {
    fontSize: 24.767 * ratio,
    color: 'black',
    fontFamily: 'Roboto-Bold',
  },
  translation: {
    fontSize: 24.767 * ratio,
    color: 'black',
    fontFamily: 'Roboto-Regular',
    textAlign: 'left',
  },
  lineBreak: {
    height: 1,
    alignSelf: 'stretch',
    backgroundColor: grey,
  },
  darkLineBreak: {
    height: 1,
    alignSelf: 'stretch',
    backgroundColor: '#a6a6a6',
  },
  list: {
    // width: width,
    // flex: 1,
    // alignSelf: 'center',
  },
  row: {
    width: width,
    alignItems: 'center',
    alignSelf: 'stretch',
    justifyContent: 'space-around',
    backgroundColor: 'transparent',
  },
  imageContainer: {
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    height: imageWidth - 120 * ratio,
    width: imageWidth - 120 * ratio,
    backgroundColor: 'white',
    margin: 5,
  },
  image: {
    flexDirection: 'row',
    width: imageWidth - 120 * ratio,
    height: imageWidth - 120 * ratio,
    justifyContent: 'flex-end',
    alignItems: 'flex-start',
    backgroundColor: 'white',
    margin: 5,
  },
  imageText: {
    color: 'black',
    fontSize: 20.639 * ratio,
    fontWeight: 'bold',
    paddingTop: 60,
    fontFamily: 'Roboto-Regular',
  },
  bodyPartEnglishOnly: {
    fontSize: 24.767 * ratio,
    color: 'black',
    paddingTop: 5,
    alignSelf: 'flex-start',
    fontFamily: 'Roboto-Regular',
    flexWrap: 'wrap',
  },
  bodyPart: {
    fontSize: 20.639 * ratio,
    color: 'black',
    paddingTop: 5,
    alignSelf: 'flex-start',
    fontFamily: 'Roboto-Bold',
  },
  bodyPartTranslation: {
    fontSize: 20.639 * ratio,
    color: 'black',
    paddingBottom: 5,
    alignSelf: 'flex-start',
    fontFamily: 'Roboto-Regular',
    flexWrap: 'wrap',
  },
  box: {
    alignSelf: 'center',
    width: 50 * ratio,
    height: 50 * ratio,
    marginLeft: 5 * ratio,
    borderWidth: 4 * ratio,
    borderColor: grey,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
  },
  tick: {
    alignSelf: 'center',
    height: 40 * ratio,
    width: 40 * ratio,
  },
  border: {
    height: 1,
    marginTop: 10,
    backgroundColor: grey,
    alignSelf: 'stretch',
  },
  bottomBar: {
    alignSelf: 'stretch',
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: adultLight,
  },
  button: {
    width: 90 * ratio,
    paddingTop: 5,
    paddingBottom: 5,
    margin: 5,
    marginLeft: 10,
    marginRight: 10,
    backgroundColor: adultDark,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    elevation: 3,
  },
  buttonText: {
    fontSize: 20.639 * ratio,
    color: 'white',
    textAlign: 'center',
    fontFamily: 'Roboto-Regular',
  },
  counter: {
    margin: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  counterText: {
    color: 'white',
    fontSize: 17.199 * ratio,
    backgroundColor: 'transparent',
    fontFamily: 'Roboto-Regular',
  },
});

